stages:
  - go-test
  - deploy

telepathy-test:
  stage: go-test
  image: golang:1.14-alpine
  services:
    - mongo:latest
  script:
    - CGO_ENABLED=0 go test -v -timeout 30s ./internal/pkg/telepathy/...

staging:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache git curl
    - |- 
        docker build --rm -t registry.heroku.com/${STAGING_APP_NAME}/web \
        --iidfile imageid.txt \
        --build-arg version=$(git rev-parse --short HEAD) .
    - docker login -u _ -p $STAGING_API_KEY registry.heroku.com
    - docker push registry.heroku.com/${STAGING_APP_NAME}/web
    - |-
        curl -X PATCH https://api.heroku.com/apps/${STAGING_APP_NAME}/formation \
        --header "Content-Type: application/json" \
        --header "Accept: application/vnd.heroku+json; version=3.docker-releases" \
        --header "Authorization: Bearer ${STAGING_API_KEY}" \
        --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
  only:
    - master